version: '3.8'

services:
  janus_server:
    build: .
    command: ['--server-name', 'TicTacToeInstance']
    ports:
      - '8088:8088'
      - '8089:8089'
      - '7088:7088'
      - '7089:7089'
      - '8188:8188'
      - '8889:8889'
      - '8000:8000'
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./conf:/opt/janus/etc/janus